=== Peter-van-Tol/LiteX-CNC/src/litexcnc/config/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "LiteX-CNC Configuration",
    "type": "object",
    "required": [
        "board_name",
        "board_type",
        "clock_frequency",
        "connection",
        "watchdog",
        "modules"
    ],
    "properties": {
        "board_name": {
            "type": "string"
        },
        "board_type": {
            "enum": [
                "5A-75B v6.1",
                "5A-75B v7.0",
                "5A-75B v8.0",
                "5A-75E v6.0",
                "5A-75E v7.1",
                "5A-75E v8.2",
                "HUB75HAT v6.1",
                "HUB75HAT v7.0",
                "HUB75HAT v8.0",
                "i5 v7.0",
                "i9 v7.2",
                "RV901T"
            ]
        },
        "clock_frequency": {
            "type": "integer",
            "minimum": 1
        },
        "connection": {
            "type": "object",
            "oneOf": [
                {
                    "$ref": "#/$defs/spiConnection"
                },
                {
                    "$ref": "#/$defs/etherboneConnection"
                }
            ]
        },
        "watchdog": {
            "type": "object",
            "properties": {
                "pin": {
                    "$ref": "#/$defs/pin"
                }
            }
        },
        "modules": {
            "type": "array",
            "items": {
                "oneOf": [
                    {
                        "$ref": "#/$defs/gpioModule"
                    },
                    {
                        "$ref": "#/$defs/pwmModule"
                    },
                    {
                        "$ref": "#/$defs/stepgenModule"
                    },
                    {
                        "$ref": "#/$defs/encoderModule"
                    }
                ]
            }
        }
    },
    "additionalProperties": false,
    "$defs": {
        "pin": {
            "type": "string"
        },

        "spiConnection": {
            "type": "object",
            "required": ["connection_type", "mosi", "miso", "clk", "cs_n"],
            "properties": {
                "connection_type": {
                    "const": "spi"
                },
                "mosi": {
                    "$ref": "#/$defs/pin"
                },
                "miso": {
                    "$ref": "#/$defs/pin"
                },
                "clk": {
                    "$ref": "#/$defs/pin"
                },
                "cs_n": {
                    "$ref": "#/$defs/pin"
                }
            },
            "additionalProperties": false
        },

        "etherboneConnection": {
            "type": "object",
            "required": ["connection_type", "ip_address", "mac_address"],
            "properties": {
                "connection_type": {
                    "const": "etherbone"
                },
                "ip_address": {
                    "type": "string",
                    "format": "ipv4"
                },
                "mac_address": {
                    "type": "string",
                    "pattern": "^0x[0-9a-fA-F]{12}$"
                },
                "rx_delay": {
                    "type": "integer",
                    "minimum": 0,
                    "default": 0
                },
                "tx_delay": {
                    "type": "integer",
                    "minimum": 0,
                    "default": 0
                },
                "with_hw_init_reset": {
                    "type": "boolean",
                    "default": false
                }
            },
            "additionalProperties": false
        },

        "gpioModule": {
            "type": "object",
            "required": ["module_type", "instances"],
            "properties": {
                "module_type": {
                    "const": "gpio"
                },
                "instances": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["direction", "pin"],
                        "properties": {
                            "direction": {
                                "enum": ["in", "out"]
                            },
                            "pin": {
                                "$ref": "#/$defs/pin"
                            },
                            "name": {
                                "type": "string"
                            },
                            "safe_state": {
                                "type": "boolean"
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        },

        "pwmModule": {
            "type": "object",
            "required": ["module_type", "instances"],
            "properties": {
                "module_type": {
                    "const": "pwm"
                },
                "instances": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["pin"],
                        "properties": {
                            "pin": {
                                "$ref": "#/$defs/pin"
                            },
                            "name": {
                                "type": "string"
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        },

        "stepgenModule": {
            "type": "object",
            "required": ["module_type", "instances"],
            "properties": {
                "module_type": {
                    "const": "stepgen"
                },
                "instances": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["pins", "soft_stop"],
                        "properties": {
                            "pins": {
                                "oneOf": [
                                    {
                                        "type": "object",
                                        "required": [
                                            "stepgen_type",
                                            "step_pin",
                                            "dir_pin"
                                        ],
                                        "properties": {
                                            "stepgen_type": {
                                                "const": "step_dir"
                                            },
                                            "step_pin": {
                                                "$ref": "#/$defs/pin"
                                            },
                                            "dir_pin": {
                                                "$ref": "#/$defs/pin"
                                            }
                                        },
                                        "additionalProperties": false
                                    },
                                    {
                                        "type": "object",
                                        "required": [
                                            "stepgen_type",
                                            "step_pos_pin",
                                            "step_neg_pin",
                                            "dir_pos_pin",
                                            "dir_neg_pin"
                                        ],
                                        "properties": {
                                            "stepgen_type": {
                                                "const": "step_dir_differential"
                                            },
                                            "step_pos_pin": {
                                                "$ref": "#/$defs/pin"
                                            },
                                            "step_neg_pin": {
                                                "$ref": "#/$defs/pin"
                                            },
                                            "dir_pos_pin": {
                                                "$ref": "#/$defs/pin"
                                            },
                                            "dir_neg_pin": {
                                                "$ref": "#/$defs/pin"
                                            }
                                        },
                                        "additionalProperties": false
                                    }
                                ]
                            },
                            "soft_stop": {
                                "type": "boolean"
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        },

        "encoderModule": {
            "type": "object",
            "required": ["module_type", "instances"],
            "properties": {
                "module_type": {
                    "const": "encoder"
                },
                "instances": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["pin_A", "pin_B"],
                        "properties": {
                            "pin_A": {
                                "$ref": "#/$defs/pin"
                            },
                            "pin_B": {
                                "$ref": "#/$defs/pin"
                            },
                            "pin_Z": {
                                "$ref": "#/$defs/pin"
                            },
                            "name": {
                                "type": "string"
                            },
                            "min_value": {
                                "type": "integer",
                                "minimum": 0
                            },
                            "max_value": {
                                "type": "integer",
                                "minimum": 0
                            },
                            "reset_value": {
                                "type": "integer",
                                "minimum": 0
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        }
    }
}

=== Peter-van-Tol/LiteX-CNC/docs/src/examples/json/5a-75b_v8.0_i24o32.json
{
    "board_name": "5A-75B:V8.0",
    "board_type": "5A-75B v8.0",
    "clock_frequency": 40000000,
    "connection": {
        "connection_type": "etherbone",
        "tx_delay": 0,
        "ip_address": "10.0.0.10",
        "mac_address": "0x10e2d5000000"
    },
    "watchdog": {
        "pin": "j1:8"
    },
    "modules": [
        {
            "module_type": "gpio",
            "instances": [
                { "direction": "out", "pin": "j1:9", "name": "j1:10" },
                { "direction": "out", "pin": "j1:10", "name": "j1:11" },
                { "direction": "out", "pin": "j1:11", "name": "j1:12" },
                { "direction": "out", "pin": "j1:12", "name": "j1:13" },
                { "direction": "out", "pin": "j1:13", "name": "j1:14" },
                { "direction": "out", "pin": "j1:14", "name": "j1:15" },
                { "direction": "in", "pin": "j1:0", "name": "j1:1" },
                { "direction": "in", "pin": "j1:1", "name": "j1:2" },
                { "direction": "in", "pin": "j1:2", "name": "j1:3" },
                { "direction": "in", "pin": "j1:4", "name": "j1:5" },
                { "direction": "in", "pin": "j1:5", "name": "j1:6" },
                { "direction": "in", "pin": "j1:6", "name": "j1:7" },
                { "direction": "in", "pin": "j2:0", "name": "j2:1" },
                { "direction": "in", "pin": "j2:1", "name": "j2:2" },
                { "direction": "in", "pin": "j2:2", "name": "j2:3" },
                { "direction": "in", "pin": "j2:4", "name": "j2:5" },
                { "direction": "in", "pin": "j2:5", "name": "j2:6" },
                { "direction": "in", "pin": "j2:6", "name": "j2:7" },
                { "direction": "in", "pin": "j3:0", "name": "j3:1" },
                { "direction": "in", "pin": "j3:1", "name": "j3:2" },
                { "direction": "in", "pin": "j3:2", "name": "j3:3" },
                { "direction": "in", "pin": "j3:4", "name": "j3:5" },
                { "direction": "in", "pin": "j3:5", "name": "j3:6" },
                { "direction": "in", "pin": "j3:6", "name": "j3:7" },
                { "direction": "in", "pin": "j4:0", "name": "j4:1" },
                { "direction": "in", "pin": "j4:1", "name": "j4:2" },
                { "direction": "in", "pin": "j4:2", "name": "j4:3" },
                { "direction": "in", "pin": "j4:4", "name": "j4:5" },
                { "direction": "in", "pin": "j4:5", "name": "j4:6" },
                { "direction": "in", "pin": "j4:6", "name": "j4:7" },
                { "direction": "out", "pin": "j5:0", "name": "j5:1" },
                { "direction": "out", "pin": "j5:1", "name": "j5:2" },
                { "direction": "out", "pin": "j5:2", "name": "j5:3" },
                { "direction": "out", "pin": "j5:4", "name": "j5:5" },
                { "direction": "out", "pin": "j5:5", "name": "j5:6" },
                { "direction": "out", "pin": "j5:6", "name": "j5:7" },
                { "direction": "out", "pin": "j6:0", "name": "j6:1" },
                { "direction": "out", "pin": "j6:1", "name": "j6:2" },
                { "direction": "out", "pin": "j6:2", "name": "j6:3" },
                { "direction": "out", "pin": "j6:4", "name": "j6:5" },
                { "direction": "out", "pin": "j6:5", "name": "j6:6" },
                { "direction": "out", "pin": "j6:6", "name": "j6:7" },
                { "direction": "out", "pin": "j7:0", "name": "j7:1" },
                { "direction": "out", "pin": "j7:1", "name": "j7:2" },
                { "direction": "out", "pin": "j7:2", "name": "j7:3" },
                { "direction": "out", "pin": "j7:4", "name": "j7:5" },
                { "direction": "out", "pin": "j7:5", "name": "j7:6" },
                { "direction": "out", "pin": "j7:6", "name": "j7:7" },
                { "direction": "out", "pin": "j8:0", "name": "j8:1" },
                { "direction": "out", "pin": "j8:1", "name": "j8:2" },
                { "direction": "out", "pin": "j8:2", "name": "j8:3" },
                { "direction": "out", "pin": "j8:4", "name": "j8:5" },
                { "direction": "out", "pin": "j8:5", "name": "j8:6" },
                { "direction": "out", "pin": "j8:6", "name": "j8:7" }
            ]
        }
    ]
}

=== Peter-van-Tol/LiteX-CNC/docs/src/examples/json/5a-75b_v7.0_i24o30.json
{
    "board_name": "5A-75B:V7.0",
    "board_type": "5A-75B v7.0",
    "clock_frequency": 40000000,
    "connection": {
        "connection_type": "etherbone",
        "tx_delay": 0,
        "ip_address": "10.0.0.10",
        "mac_address": "0x10e2d5000000"
    },
    "watchdog": {
        "pin": "j1:8"
    },
    "modules": [
        {
            "module_type": "gpio",
            "instances": [
                { "direction": "out", "pin": "j1:9", "name": "B" },
                { "direction": "out", "pin": "j1:10", "name": "C" },
                { "direction": "out", "pin": "j1:11", "name": "D" },
                { "direction": "out", "pin": "j1:12", "name": "CLK" },
                { "direction": "out", "pin": "j1:13", "name": "STB" },
                { "direction": "out", "pin": "j1:14", "name": "OE" },
                { "direction": "in", "pin": "j1:0", "name": "J1:R0" },
                { "direction": "in", "pin": "j1:1", "name": "J1:G0" },
                { "direction": "in", "pin": "j1:2", "name": "J1:B0" },
                { "direction": "in", "pin": "j1:4", "name": "J1:R1" },
                { "direction": "in", "pin": "j1:5", "name": "J1:G1" },
                { "direction": "in", "pin": "j1:6", "name": "J1:B1" },
                { "direction": "in", "pin": "j2:0", "name": "J2:R0" },
                { "direction": "in", "pin": "j2:1", "name": "J2:G0" },
                { "direction": "in", "pin": "j2:2", "name": "J2:B0" },
                { "direction": "in", "pin": "j2:4", "name": "J2:R1" },
                { "direction": "in", "pin": "j2:5", "name": "J2:G1" },
                { "direction": "in", "pin": "j2:6", "name": "J2:B1" },
                { "direction": "in", "pin": "j3:0", "name": "J3:R0" },
                { "direction": "in", "pin": "j3:1", "name": "J3:G0" },
                { "direction": "in", "pin": "j3:2", "name": "J3:B0" },
                { "direction": "in", "pin": "j3:4", "name": "J3:R1" },
                { "direction": "in", "pin": "j3:5", "name": "J3:G1" },
                { "direction": "in", "pin": "j3:6", "name": "J3:B1" },
                { "direction": "in", "pin": "j4:0", "name": "J4:R0" },
                { "direction": "in", "pin": "j4:1", "name": "J4:G0" },
                { "direction": "in", "pin": "j4:2", "name": "J4:B0" },
                { "direction": "in", "pin": "j4:4", "name": "J4:R1" },
                { "direction": "in", "pin": "j4:5", "name": "J4:G1" },
                { "direction": "in", "pin": "j4:6", "name": "J4:B1" },
                { "direction": "out", "pin": "j5:0", "name": "J5:R0" },
                { "direction": "out", "pin": "j5:1", "name": "J5:G0" },
                { "direction": "out", "pin": "j5:2", "name": "J5:B0" },
                { "direction": "out", "pin": "j5:4", "name": "J5:R1" },
                { "direction": "out", "pin": "j5:5", "name": "J5:G1" },
                { "direction": "out", "pin": "j5:6", "name": "J5:B1" },
                { "direction": "out", "pin": "j6:0", "name": "J6:R0" },
                { "direction": "out", "pin": "j6:1", "name": "J6:G0" },
                { "direction": "out", "pin": "j6:2", "name": "J6:B0" },
                { "direction": "out", "pin": "j6:4", "name": "J6:R1" },
                { "direction": "out", "pin": "j6:5", "name": "J6:G1" },
                { "direction": "out", "pin": "j6:6", "name": "J6:B1" },
                { "direction": "out", "pin": "j7:0", "name": "J7:R0" },
                { "direction": "out", "pin": "j7:1", "name": "J7:G0" },
                { "direction": "out", "pin": "j7:2", "name": "J7:B0" },
                { "direction": "out", "pin": "j7:4", "name": "J7:R1" },
                { "direction": "out", "pin": "j7:5", "name": "J7:G1" },
                { "direction": "out", "pin": "j7:6", "name": "J7:B1" },
                { "direction": "out", "pin": "j8:0", "name": "J8:R0" },
                { "direction": "out", "pin": "j8:1", "name": "J8:G0" },
                { "direction": "out", "pin": "j8:2", "name": "J8:B0" },
                { "direction": "out", "pin": "j8:4", "name": "J8:R1" },
                { "direction": "out", "pin": "j8:5", "name": "J8:G1" },
                { "direction": "out", "pin": "j8:6", "name": "J8:B1" }
            ]
        }
    ]
}

=== Peter-van-Tol/LiteX-CNC/docs/src/examples/json/5a-75e_v8.2_o100p4.json
{
    "board_name": "5A-75E:V8.2",
    "board_type": "5A-75E v8.2",
    "clock_frequency": 40000000,
    "connection": {
        "connection_type": "etherbone",
        "tx_delay": 0,
        "ip_address": "10.0.0.10",
        "mac_address": "0x10e2d5000000"
    },
    "watchdog": {},
    "modules": [
        {
            "module_type": "pwm",
            "instances": [
                { "pin": "j1:0", "name": "J1:R0" },
                { "pin": "j1:1", "name": "J1:G0" },
                { "pin": "j1:2", "name": "J1:B0" },
                { "pin": "j1:4", "name": "J1:R1" }
            ]
        },
        {
            "module_type": "gpio",
            "instances": [
                { "direction": "out", "pin": "j1:7", "name": "E" },
                { "direction": "out", "pin": "j1:8", "name": "A" },
                { "direction": "out", "pin": "j1:9", "name": "B" },
                { "direction": "out", "pin": "j1:10", "name": "C" },
                { "direction": "out", "pin": "j1:11", "name": "D" },
                { "direction": "out", "pin": "j1:12", "name": "CLK" },
                { "direction": "out", "pin": "j1:13", "name": "STB" },
                { "direction": "out", "pin": "j1:14", "name": "OE" },
                { "direction": "out", "pin": "j1:5", "name": "J1:G1" },
                { "direction": "out", "pin": "j1:6", "name": "J1:B1" },
                { "direction": "out", "pin": "j2:0", "name": "J2:R0" },
                { "direction": "out", "pin": "j2:1", "name": "J2:G0" },
                { "direction": "out", "pin": "j2:2", "name": "J2:B0" },
                { "direction": "out", "pin": "j2:4", "name": "J2:R1" },
                { "direction": "out", "pin": "j2:5", "name": "J2:G1" },
                { "direction": "out", "pin": "j2:6", "name": "J2:B1" },
                { "direction": "out", "pin": "j3:0", "name": "J3:R0" },
                { "direction": "out", "pin": "j3:1", "name": "J3:G0" },
                { "direction": "out", "pin": "j3:2", "name": "J3:B0" },
                { "direction": "out", "pin": "j3:4", "name": "J3:R1" },
                { "direction": "out", "pin": "j3:5", "name": "J3:G1" },
                { "direction": "out", "pin": "j3:6", "name": "J3:B1" },
                { "direction": "out", "pin": "j4:0", "name": "J4:R0" },
                { "direction": "out", "pin": "j4:1", "name": "J4:G0" },
                { "direction": "out", "pin": "j4:2", "name": "J4:B0" },
                { "direction": "out", "pin": "j4:4", "name": "J4:R1" },
                { "direction": "out", "pin": "j4:5", "name": "J4:G1" },
                { "direction": "out", "pin": "j4:6", "name": "J4:B1" },
                { "direction": "out", "pin": "j5:0", "name": "J5:R0" },
                { "direction": "out", "pin": "j5:1", "name": "J5:G0" },
                { "direction": "out", "pin": "j5:2", "name": "J5:B0" },
                { "direction": "out", "pin": "j5:4", "name": "J5:R1" },
                { "direction": "out", "pin": "j5:5", "name": "J5:G1" },
                { "direction": "out", "pin": "j5:6", "name": "J5:B1" },
                { "direction": "out", "pin": "j6:0", "name": "J6:R0" },
                { "direction": "out", "pin": "j6:1", "name": "J6:G0" },
                { "direction": "out", "pin": "j6:2", "name": "J6:B0" },
                { "direction": "out", "pin": "j6:4", "name": "J6:R1" },
                { "direction": "out", "pin": "j6:5", "name": "J6:G1" },
                { "direction": "out", "pin": "j6:6", "name": "J6:B1" },
                { "direction": "out", "pin": "j7:0", "name": "J7:R0" },
                { "direction": "out", "pin": "j7:1", "name": "J7:G0" },
                { "direction": "out", "pin": "j7:2", "name": "J7:B0" },
                { "direction": "out", "pin": "j7:4", "name": "J7:R1" },
                { "direction": "out", "pin": "j7:5", "name": "J7:G1" },
                { "direction": "out", "pin": "j7:6", "name": "J7:B1" },
                { "direction": "out", "pin": "j8:0", "name": "J8:R0" },
                { "direction": "out", "pin": "j8:1", "name": "J8:G0" },
                { "direction": "out", "pin": "j8:2", "name": "J8:B0" },
                { "direction": "out", "pin": "j8:4", "name": "J8:R1" },
                { "direction": "out", "pin": "j8:5", "name": "J8:G1" },
                { "direction": "out", "pin": "j8:6", "name": "J8:B1" },
                { "direction": "out", "pin": "j9:0", "name": "J9:R0" },
                { "direction": "out", "pin": "j9:1", "name": "J9:G0" },
                { "direction": "out", "pin": "j9:2", "name": "J9:B0" },
                { "direction": "out", "pin": "j9:4", "name": "J9:R1" },
                { "direction": "out", "pin": "j9:5", "name": "J9:G1" },
                { "direction": "out", "pin": "j9:6", "name": "J9:B1" },
                { "direction": "out", "pin": "j10:0", "name": "J10:R0" },
                { "direction": "out", "pin": "j10:1", "name": "J10:G0" },
                { "direction": "out", "pin": "j10:2", "name": "J10:B0" },
                { "direction": "out", "pin": "j10:4", "name": "J10:R1" },
                { "direction": "out", "pin": "j10:5", "name": "J10:G1" },
                { "direction": "out", "pin": "j10:6", "name": "J10:B1" },
                { "direction": "out", "pin": "j11:0", "name": "J11:R0" },
                { "direction": "out", "pin": "j11:1", "name": "J11:G0" },
                { "direction": "out", "pin": "j11:2", "name": "J11:B0" },
                { "direction": "out", "pin": "j11:4", "name": "J11:R1" },
                { "direction": "out", "pin": "j11:5", "name": "J11:G1" },
                { "direction": "out", "pin": "j11:6", "name": "J11:B1" },
                { "direction": "out", "pin": "j12:0", "name": "J12:R0" },
                { "direction": "out", "pin": "j12:1", "name": "J12:G0" },
                { "direction": "out", "pin": "j12:2", "name": "J12:B0" },
                { "direction": "out", "pin": "j12:4", "name": "J12:R1" },
                { "direction": "out", "pin": "j12:5", "name": "J12:G1" },
                { "direction": "out", "pin": "j12:6", "name": "J12:B1" },
                { "direction": "out", "pin": "j13:0", "name": "J13:R0" },
                { "direction": "out", "pin": "j13:1", "name": "J13:G0" },
                { "direction": "out", "pin": "j13:2", "name": "J13:B0" },
                { "direction": "out", "pin": "j13:4", "name": "J13:R1" },
                { "direction": "out", "pin": "j13:5", "name": "J13:G1" },
                { "direction": "out", "pin": "j13:6", "name": "J13:B1" },
                { "direction": "out", "pin": "j14:0", "name": "J14:R0" },
                { "direction": "out", "pin": "j14:1", "name": "J14:G0" },
                { "direction": "out", "pin": "j14:2", "name": "J14:B0" },
                { "direction": "out", "pin": "j14:4", "name": "J14:R1" },
                { "direction": "out", "pin": "j14:5", "name": "J14:G1" },
                { "direction": "out", "pin": "j14:6", "name": "J14:B1" },
                { "direction": "out", "pin": "j15:0", "name": "J15:R0" },
                { "direction": "out", "pin": "j15:1", "name": "J15:G0" },
                { "direction": "out", "pin": "j15:2", "name": "J15:B0" },
                { "direction": "out", "pin": "j15:4", "name": "J15:R1" },
                { "direction": "out", "pin": "j15:5", "name": "J15:G1" },
                { "direction": "out", "pin": "j15:6", "name": "J15:B1" },
                { "direction": "out", "pin": "j16:0", "name": "J16:R0" },
                { "direction": "out", "pin": "j16:1", "name": "J16:G0" },
                { "direction": "out", "pin": "j16:2", "name": "J16:B0" },
                { "direction": "out", "pin": "j16:4", "name": "J16:R1" },
                { "direction": "out", "pin": "j16:5", "name": "J16:G1" },
                { "direction": "out", "pin": "j16:6", "name": "J16:B1" }
            ]
        }
    ]
}
