=== Peter-van-Tol/LiteX-CNC/src/litexcnc/config/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "LiteX-CNC Configuration",
    "type": "object",
    "required": [
        "board_name",
        "board_type",
        "clock_frequency",
        "connection",
        "watchdog",
        "modules"
    ],
    "properties": {
        "board_name": {
            "type": "string"
        },
        "board_type": {
            "enum": [
                "5A-75B v6.1",
                "5A-75B v7.0",
                "5A-75B v8.0",
                "5A-75E v6.0",
                "5A-75E v7.1",
                "5A-75E v8.2",
                "HUB75HAT v6.1",
                "HUB75HAT v7.0",
                "HUB75HAT v8.0",
                "i5 v7.0",
                "i9 v7.2",
                "RV901T"
            ]
        },
        "clock_frequency": {
            "type": "integer",
            "minimum": 1
        },
        "connection": {
            "type": "object",
            "oneOf": [
                {
                    "$ref": "#/$defs/spiConnection"
                },
                {
                    "$ref": "#/$defs/etherboneConnection"
                }
            ]
        },
        "watchdog": {
            "type": "object",
            "properties": {
                "pin": {
                    "$ref": "#/$defs/pin"
                }
            }
        },
        "modules": {
            "type": "array",
            "items": {
                "oneOf": [
                    {
                        "$ref": "#/$defs/gpioModule"
                    },
                    {
                        "$ref": "#/$defs/pwmModule"
                    },
                    {
                        "$ref": "#/$defs/stepgenModule"
                    },
                    {
                        "$ref": "#/$defs/encoderModule"
                    }
                ]
            }
        }
    },
    "additionalProperties": false,
    "$defs": {
        "pin": {
            "type": "string"
        },

        "spiConnection": {
            "type": "object",
            "required": ["connection_type", "mosi", "miso", "clk", "cs_n"],
            "properties": {
                "connection_type": {
                    "const": "spi"
                },
                "mosi": {
                    "$ref": "#/$defs/pin"
                },
                "miso": {
                    "$ref": "#/$defs/pin"
                },
                "clk": {
                    "$ref": "#/$defs/pin"
                },
                "cs_n": {
                    "$ref": "#/$defs/pin"
                }
            },
            "additionalProperties": false
        },

        "etherboneConnection": {
            "type": "object",
            "required": ["connection_type", "ip_address", "mac_address"],
            "properties": {
                "connection_type": {
                    "const": "etherbone"
                },
                "ip_address": {
                    "type": "string",
                    "format": "ipv4"
                },
                "mac_address": {
                    "type": "string",
                    "pattern": "^0x[0-9a-fA-F]{12}$"
                },
                "rx_delay": {
                    "type": "integer",
                    "minimum": 0,
                    "default": 0
                },
                "tx_delay": {
                    "type": "integer",
                    "minimum": 0,
                    "default": 0
                },
                "with_hw_init_reset": {
                    "type": "boolean",
                    "default": false
                }
            },
            "additionalProperties": false
        },

        "gpioModule": {
            "type": "object",
            "required": ["module_type", "instances"],
            "properties": {
                "module_type": {
                    "const": "gpio"
                },
                "instances": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["direction", "pin"],
                        "properties": {
                            "direction": {
                                "enum": ["in", "out"]
                            },
                            "pin": {
                                "$ref": "#/$defs/pin"
                            },
                            "name": {
                                "type": "string"
                            },
                            "safe_state": {
                                "type": "boolean"
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        },

        "pwmModule": {
            "type": "object",
            "required": ["module_type", "instances"],
            "properties": {
                "module_type": {
                    "const": "pwm"
                },
                "instances": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["pin"],
                        "properties": {
                            "pin": {
                                "$ref": "#/$defs/pin"
                            },
                            "name": {
                                "type": "string"
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        },

        "stepgenModule": {
            "type": "object",
            "required": ["module_type", "instances"],
            "properties": {
                "module_type": {
                    "const": "stepgen"
                },
                "instances": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["pins", "soft_stop"],
                        "properties": {
                            "pins": {
                                "oneOf": [
                                    {
                                        "type": "object",
                                        "required": [
                                            "stepgen_type",
                                            "step_pin",
                                            "dir_pin"
                                        ],
                                        "properties": {
                                            "stepgen_type": {
                                                "const": "step_dir"
                                            },
                                            "step_pin": {
                                                "$ref": "#/$defs/pin"
                                            },
                                            "dir_pin": {
                                                "$ref": "#/$defs/pin"
                                            }
                                        },
                                        "additionalProperties": false
                                    },
                                    {
                                        "type": "object",
                                        "required": [
                                            "stepgen_type",
                                            "step_pos_pin",
                                            "step_neg_pin",
                                            "dir_pos_pin",
                                            "dir_neg_pin"
                                        ],
                                        "properties": {
                                            "stepgen_type": {
                                                "const": "step_dir_differential"
                                            },
                                            "step_pos_pin": {
                                                "$ref": "#/$defs/pin"
                                            },
                                            "step_neg_pin": {
                                                "$ref": "#/$defs/pin"
                                            },
                                            "dir_pos_pin": {
                                                "$ref": "#/$defs/pin"
                                            },
                                            "dir_neg_pin": {
                                                "$ref": "#/$defs/pin"
                                            }
                                        },
                                        "additionalProperties": false
                                    }
                                ]
                            },
                            "soft_stop": {
                                "type": "boolean"
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        },

        "encoderModule": {
            "type": "object",
            "required": ["module_type", "instances"],
            "properties": {
                "module_type": {
                    "const": "encoder"
                },
                "instances": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["pin_A", "pin_B"],
                        "properties": {
                            "pin_A": {
                                "$ref": "#/$defs/pin"
                            },
                            "pin_B": {
                                "$ref": "#/$defs/pin"
                            },
                            "pin_Z": {
                                "$ref": "#/$defs/pin"
                            },
                            "name": {
                                "type": "string"
                            },
                            "min_value": {
                                "type": "integer",
                                "minimum": 0
                            },
                            "max_value": {
                                "type": "integer",
                                "minimum": 0
                            },
                            "reset_value": {
                                "type": "integer",
                                "minimum": 0
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        }
    }
}

=== Peter-van-Tol/LiteX-CNC/docs/src/examples/json/5a-75b_v8.0_i12o14p6s6e6.json
{
    "board_name": "5A-75B:V8.0",
    "board_type": "5A-75B v8.0",
    "clock_frequency": 40000000,
    "connection": {
        "connection_type": "etherbone",
        "tx_delay": 0,
        "ip_address": "10.0.0.10",
        "mac_address": "0x10e2d5000000"
    },
    "watchdog": {
        "pin": "j1:8"
    },
    "modules": [
        {
            "module_type": "gpio",
            "instances": [
                {
                    "direction": "out",
                    "pin": "j1:9",
                    "name": "j1:10"
                },
                {
                    "direction": "out",
                    "pin": "j1:10",
                    "name": "j1:11"
                },
                {
                    "direction": "out",
                    "pin": "j1:11",
                    "name": "j1:12"
                },
                {
                    "direction": "out",
                    "pin": "j1:12",
                    "name": "j1:13"
                },
                {
                    "direction": "out",
                    "pin": "j1:13",
                    "name": "j1:14"
                },
                {
                    "direction": "out",
                    "pin": "j1:14",
                    "name": "j1:15"
                },
                {
                    "direction": "in",
                    "pin": "j1:0",
                    "name": "j1:1"
                },
                {
                    "direction": "in",
                    "pin": "j1:1",
                    "name": "j1:2"
                },
                {
                    "direction": "in",
                    "pin": "j1:2",
                    "name": "j1:3"
                },
                {
                    "direction": "in",
                    "pin": "j1:4",
                    "name": "j1:5"
                },
                {
                    "direction": "in",
                    "pin": "j1:5",
                    "name": "j1:6"
                },
                {
                    "direction": "in",
                    "pin": "j1:6",
                    "name": "j1:7"
                },
                {
                    "direction": "in",
                    "pin": "j2:0",
                    "name": "j2:1"
                },
                {
                    "direction": "in",
                    "pin": "j2:1",
                    "name": "j2:2"
                },
                {
                    "direction": "in",
                    "pin": "j2:2",
                    "name": "j2:3"
                },
                {
                    "direction": "in",
                    "pin": "j2:4",
                    "name": "j2:5"
                },
                {
                    "direction": "in",
                    "pin": "j2:5",
                    "name": "j2:6"
                },
                {
                    "direction": "in",
                    "pin": "j2:6",
                    "name": "j2:7"
                },
                {
                    "direction": "out",
                    "pin": "j5:0",
                    "name": "j5:1"
                },
                {
                    "direction": "out",
                    "pin": "j5:1",
                    "name": "j5:2"
                },
                {
                    "direction": "out",
                    "pin": "j5:2",
                    "name": "j5:3"
                },
                {
                    "direction": "out",
                    "pin": "j5:4",
                    "name": "j5:5"
                },
                {
                    "direction": "out",
                    "pin": "j5:5",
                    "name": "j5:6"
                },
                {
                    "direction": "out",
                    "pin": "j5:6",
                    "name": "j5:7"
                }
            ]
        },
        {
            "module_type": "pwm",
            "instances": [
                {
                    "pin": "j6:0",
                    "name": "j6:1"
                },
                {
                    "pin": "j6:1",
                    "name": "j6:2"
                },
                {
                    "pin": "j6:2",
                    "name": "j6:3"
                },
                {
                    "pin": "j6:4",
                    "name": "j6:5"
                },
                {
                    "pin": "j6:5",
                    "name": "j6:6"
                },
                {
                    "pin": "j6:6",
                    "name": "j6:7"
                }
            ]
        },
        {
            "module_type": "encoder",
            "instances": [
                {
                    "pin_A": "j3:0",
                    "pin_B": "j3:1"
                },
                {
                    "pin_A": "j3:2",
                    "pin_B": "j3:4"
                },
                {
                    "pin_A": "j3:5",
                    "pin_B": "j3:6"
                },
                {
                    "pin_A": "j4:0",
                    "pin_B": "j4:1"
                },
                {
                    "pin_A": "j4:2",
                    "pin_B": "j4:4"
                },
                {
                    "pin_A": "j4:5",
                    "pin_B": "j4:6"
                }
            ]
        },
        {
            "module_type": "stepgen",
            "instances": [
                {
                    "pins": {
                        "stepgen_type": "step_dir",
                        "step_pin": "j7:0",
                        "dir_pin": "j7:1"
                    },
                    "soft_stop": true
                },
                {
                    "pins": {
                        "stepgen_type": "step_dir",
                        "step_pin": "j7:2",
                        "dir_pin": "j7:4"
                    },
                    "soft_stop": true
                },
                {
                    "pins": {
                        "stepgen_type": "step_dir",
                        "step_pin": "j7:5",
                        "dir_pin": "j7:6"
                    },
                    "soft_stop": true
                },
                {
                    "pins": {
                        "stepgen_type": "step_dir",
                        "step_pin": "j8:0",
                        "dir_pin": "j8:1"
                    },
                    "soft_stop": true
                },
                {
                    "pins": {
                        "stepgen_type": "step_dir",
                        "step_pin": "j8:2",
                        "dir_pin": "j8:4"
                    },
                    "soft_stop": true
                },
                {
                    "pins": {
                        "stepgen_type": "step_dir",
                        "step_pin": "j8:5",
                        "dir_pin": "j8:6"
                    },
                    "soft_stop": true
                }
            ]
        }
    ]
}

=== Peter-van-Tol/LiteX-CNC/docs/src/examples/json/5a-75e_v6.0_i48o56.json
{
    "board_name": "5A-75B:V6.0",
    "board_type": "5A-75E v6.0",
    "clock_frequency": 40000000,
    "connection": {
        "connection_type": "etherbone",
        "tx_delay": 0,
        "ip_address": "10.0.0.10",
        "mac_address": "0x10e2d5000000"
    },
    "watchdog": {
        "pin":"j1:8"
    },
    "modules": [
        {
            "module_type": "gpio",
            "instances": [
                {"direction": "in",  "pin":"j1:0",  "name":"j1:1"},
                {"direction": "in",  "pin":"j1:1",  "name":"j1:2"},
                {"direction": "in",  "pin":"j1:2",  "name":"j1:3"},
                {"direction": "in",  "pin":"j1:4",  "name":"j1:5"},
                {"direction": "in",  "pin":"j1:5",  "name":"j1:6"},
                {"direction": "in",  "pin":"j1:6",  "name":"j1:7"},
                {"direction": "in",  "pin":"j1:7",  "name":"j1:8"},
                {"direction": "out", "pin":"j1:9" , "name":"j1:10"},
                {"direction": "out", "pin":"j1:10", "name":"j1:11"},
                {"direction": "out", "pin":"j1:11", "name":"j1:12"},
                {"direction": "out", "pin":"j1:12", "name":"j1:13"},
                {"direction": "out", "pin":"j1:13", "name":"j1:14"},
                {"direction": "out", "pin":"j1:14", "name":"j1:15"},
                {"direction": "in",  "pin":"j2:0",  "name":"j2:1"},
                {"direction": "in",  "pin":"j2:1",  "name":"j2:2"},
                {"direction": "in",  "pin":"j2:2",  "name":"j2:3"},
                {"direction": "in",  "pin":"j2:4",  "name":"j2:5"},
                {"direction": "in",  "pin":"j2:5",  "name":"j2:6"},
                {"direction": "in",  "pin":"j2:6",  "name":"j2:7"},
                {"direction": "in",  "pin":"j3:0",  "name":"j3:1"},
                {"direction": "in",  "pin":"j3:1",  "name":"j3:2"},
                {"direction": "in",  "pin":"j3:2",  "name":"j3:3"},
                {"direction": "in",  "pin":"j3:4",  "name":"j3:5"},
                {"direction": "in",  "pin":"j3:5",  "name":"j3:6"},
                {"direction": "in",  "pin":"j3:6",  "name":"j3:7"},
                {"direction": "in",  "pin":"j4:0",  "name":"j4:1"},
                {"direction": "in",  "pin":"j4:1",  "name":"j4:2"},
                {"direction": "in",  "pin":"j4:2",  "name":"j4:3"},
                {"direction": "in",  "pin":"j4:4",  "name":"j4:5"},
                {"direction": "in",  "pin":"j4:5",  "name":"j4:6"},
                {"direction": "in",  "pin":"j4:6",  "name":"j4:7"},
                {"direction": "in",  "pin":"j5:0",  "name":"j5:1"},
                {"direction": "in",  "pin":"j5:1",  "name":"j5:2"},
                {"direction": "in",  "pin":"j5:2",  "name":"j5:3"},
                {"direction": "in",  "pin":"j5:4",  "name":"j5:5"},
                {"direction": "in",  "pin":"j5:5",  "name":"j5:6"},
                {"direction": "in",  "pin":"j5:6",  "name":"j5:7"},
                {"direction": "in",  "pin":"j6:0",  "name":"j6:1"},
                {"direction": "in",  "pin":"j6:1",  "name":"j6:2"},
                {"direction": "in",  "pin":"j6:2",  "name":"j6:3"},
                {"direction": "in",  "pin":"j6:4",  "name":"j6:5"},
                {"direction": "in",  "pin":"j6:5",  "name":"j6:6"},
                {"direction": "in",  "pin":"j6:6",  "name":"j6:7"},
                {"direction": "in",  "pin":"j7:0",  "name":"j7:1"},
                {"direction": "in",  "pin":"j7:1",  "name":"j7:2"},
                {"direction": "in",  "pin":"j7:2",  "name":"j7:3"},
                {"direction": "in",  "pin":"j7:4",  "name":"j7:5"},
                {"direction": "in",  "pin":"j7:5",  "name":"j7:6"},
                {"direction": "in",  "pin":"j7:6",  "name":"j7:7"},
                {"direction": "in",  "pin":"j8:0",  "name":"j8:1"},
                {"direction": "in",  "pin":"j8:1",  "name":"j8:2"},
                {"direction": "in",  "pin":"j8:2",  "name":"j8:3"},
                {"direction": "in",  "pin":"j8:4",  "name":"j8:5"},
                {"direction": "in",  "pin":"j8:5",  "name":"j8:6"},
                {"direction": "in",  "pin":"j8:6",  "name":"j8:7"},
                {"direction": "out", "pin":"j9:0",  "name":"j9:1"},
                {"direction": "out", "pin":"j9:1",  "name":"j9:2"},
                {"direction": "out", "pin":"j9:2",  "name":"j9:3"},
                {"direction": "out", "pin":"j9:4",  "name":"j9:5"},
                {"direction": "out", "pin":"j9:5",  "name":"j9:6"},
                {"direction": "out", "pin":"j9:6",  "name":"j9:7"},
                {"direction": "out", "pin":"j10:0", "name":"j10:1"},
                {"direction": "out", "pin":"j10:1", "name":"j10:2"},
                {"direction": "out", "pin":"j10:2", "name":"j10:3"},
                {"direction": "out", "pin":"j10:4", "name":"j10:5"},
                {"direction": "out", "pin":"j10:5", "name":"j10:6"},
                {"direction": "out", "pin":"j10:6", "name":"j10:7"},
                {"direction": "out", "pin":"j11:0", "name":"j11:1"},
                {"direction": "out", "pin":"j11:1", "name":"j11:2"},
                {"direction": "out", "pin":"j11:2", "name":"j11:3"},
                {"direction": "out", "pin":"j11:4", "name":"j11:5"},
                {"direction": "out", "pin":"j11:5", "name":"j11:6"},
                {"direction": "out", "pin":"j11:6", "name":"j11:7"},
                {"direction": "out", "pin":"j12:0", "name":"j12:1"},
                {"direction": "out", "pin":"j12:1", "name":"j12:2"},
                {"direction": "out", "pin":"j12:2", "name":"j12:3"},
                {"direction": "out", "pin":"j12:4", "name":"j12:5"},
                {"direction": "out", "pin":"j12:5", "name":"j12:6"},
                {"direction": "out", "pin":"j12:6", "name":"j12:7"},
                {"direction": "out", "pin":"j13:0", "name":"j13:1"},
                {"direction": "out", "pin":"j13:1", "name":"j13:2"},
                {"direction": "out", "pin":"j13:2", "name":"j13:3"},
                {"direction": "out", "pin":"j13:4", "name":"j13:5"},
                {"direction": "out", "pin":"j13:5", "name":"j13:6"},
                {"direction": "out", "pin":"j13:6", "name":"j13:7"},
                {"direction": "out", "pin":"j14:0", "name":"j14:1"},
                {"direction": "out", "pin":"j14:1", "name":"j14:2"},
                {"direction": "out", "pin":"j14:2", "name":"j14:3"},
                {"direction": "out", "pin":"j14:4", "name":"j14:5"},
                {"direction": "out", "pin":"j14:5", "name":"j14:6"},
                {"direction": "out", "pin":"j14:6", "name":"j14:7"},
                {"direction": "out", "pin":"j15:0", "name":"j15:1"},
                {"direction": "out", "pin":"j15:1", "name":"j15:2"},
                {"direction": "out", "pin":"j15:2", "name":"j15:3"},
                {"direction": "out", "pin":"j15:4", "name":"j15:5"},
                {"direction": "out", "pin":"j15:5", "name":"j15:6"},
                {"direction": "out", "pin":"j15:6", "name":"j15:7"},
                {"direction": "out", "pin":"j16:0", "name":"j16:1"},
                {"direction": "out", "pin":"j16:1", "name":"j16:2"},
                {"direction": "out", "pin":"j16:2", "name":"j16:3"},
                {"direction": "out", "pin":"j16:4", "name":"j16:5"},
                {"direction": "out", "pin":"j16:5", "name":"j16:6"},
                {"direction": "out", "pin":"j16:6", "name":"j16:7"}
            ]
        }
    ]
}
